apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: dealers-database
spec:
  serviceName: dealers-database
  selector:
    matchLabels:
     database: dealers
  template:
   metadata:
    labels:
     database: dealers
     system: database
   spec: 
    terminationGracePeriodSeconds: 60 #We put a termination grace period because databases are usually heavy applications and need some time to shut down successfully
    containers:
     - name: dealers-database
       image: mcr.microsoft.com/mssql/server:2019-latest
       imagePullPolicy: IfNotPresent #prevent unnecessary downloads by caching with the “IfNotPresent” policy
       ports:
       - containerPort: 1433
       resources:
        limits:
         memory: "2Gi"
         cpu: "500m"
       env:
       - name: ACCEPT_EULA
         value: "Y"
       - name: SA_PASSWORD
         valueFrom:
          secretKeyRef:
           name: environment-secrets
           key: dealers-database-sa-password
       volumeMounts:
         - mountPath: /var/opt/mssql
           name: dealers-database-data
    volumes:
     - name: dealers-database-data
       persistentVolumeClaim:
           claimName: dealers-database-data
        
