apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: identity-database-data
spec:
  accessModes:
  - ReadWriteOnce #because I have single replication of database. I don't need multiple pods using the volume
                  # If no storage class is set in the persistent volume claim, the cluster will provide a volume from its default configuration:
                  #  - In a local environment - it will be the development machine’s hard disk ("hostpath").
                  #  - In a production environment – it depends on the cloud or the cluster infrastructure.
  resources:
    requests:
      storage: 10Gi