apiVersion: v1
kind: Service
metadata:
  name: identity-database
spec:
  #type: LoadBalancer #if i want to connect to db externally - MS Management tools/Data grip
  clusterIP: None
  ports:
  - port: 1433
    targetPort: 1433
  selector:
    database: identity