apiVersion: v1
kind: Service
metadata:
  name: statistics-database
spec:
  #type: LoadBalancer #if i want to connect to db externally - MS Management tools/Data grip
  clusterIP: None
  selector:
    database: statistics
  ports:
  - port: 1433
    targetPort: 1433
