apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dealers-service-data
spec:
 accessModes:
 - "ReadWriteOnce"
 resources:
  requests:
   storage: 10Mi

---

apiVersion: v1
kind: Service
metadata:
  name: dealers-service
spec:
  type: LoadBalancer
  ports:
  - port: 5002
    targetPort: 80
  selector:
    web-service: my-dealers

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealers-service
spec:
  selector:
    matchLabels:
      web-service: my-dealers
  template:
    metadata:
      labels:
        web-service: my-dealers
        system: server
    spec:
      containers:
      - name: dealers-service
        image: andriyankrastev/carrentalsystem-dealers-service:1.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
          - name: ConnectionStrings__DefaultConnection
            valueFrom: 
             secretKeyRef:
              name: environment-secrets
              key: dealers-service-connection-string
          - name: ConnectionStrings__CronJobsConnection
            valueFrom: 
             secretKeyRef:
              name: environment-secrets
              key: dealers-service-cron-jobs-connection-string   
          - name: MessageQueueSettings__Host
            valueFrom:
              configMapKeyRef:
                name: environment-settings
                key: event-bus-host
          - name: MessageQueueSettings__UserName
            valueFrom:
              configMapKeyRef:
                name: environment-settings
                key: event-bus-user
          - name: MessageQueueSettings__Password
            valueFrom:
              secretKeyRef:
                name: environment-secrets
                key: event-bus-password     
          - name: ApplicationSettings__Secret
            valueFrom:
              secretKeyRef:
                name: environment-secrets
                key: security-token-secret
          - name: ApplicationSettings__SeedInitialData
            valueFrom:
              configMapKeyRef:
                name: environment-settings
                key: seed-initial-data
        ports:
        - containerPort: 80
        volumeMounts:
        - name: container-dealers-service-data
          mountPath: /root/.aspnet/DataProtection-Keys
      volumes:
      - name: container-dealers-service-data
        persistentVolumeClaim:
         claimName: dealers-service-data

