apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notification-service-data
spec:
 accessModes:
 - "ReadWriteOnce"
 resources:
  requests:
   storage: 10Mi

---

apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: LoadBalancer
  ports:
  - port: 5004
    targetPort: 80
  selector:
    web-service: notification

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  selector:
    matchLabels:
      web-service: notification
  template:
    metadata:
      labels:
        web-service: notification
        system: server
    spec:
      containers:
      - name: notification-service
        image: andriyankrastev/carrentalsystem-notifications-service:1.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
          - name: ApplicationSettings__Secret
            valueFrom:
              secretKeyRef:
                name: environment-secrets
                key: security-token-secret
          - name: NotificationSettings__AllowedOrigins
            valueFrom:
              configMapKeyRef:
                name: environment-settings
                key: notifications-allowed-origins
          - name: MessageQueueSettings__Host
            valueFrom:
              configMapKeyRef:
                name: environment-settings
                key: event-bus-host
          - name: MessageQueueSettings__UserName
            valueFrom:
              configMapKeyRef:
                name: environment-settings
                key: event-bus-user
          - name: MessageQueueSettings__Password
            valueFrom:
              secretKeyRef:
                name: environment-secrets
                key: event-bus-password
        ports:
        - containerPort: 80
        volumeMounts:
        - name: notification-service-data
          mountPath: /root/.aspnet/DataProtection-Keys
      volumes:
      - name: notification-service-data
        persistentVolumeClaim:
         claimName: notification-service-data

